version: '2'

services:

  phpfpm:
    image: phpfpm
    container_name: phpfpm
    restart: on-failure
    volumes:
      - ./web:/code

  mariadb:
    image: mariadb:latest
    restart: on-failure
    volumes:
      - ./mariadb/create.sql:/docker-entrypoint-initdb.d/create.sql
      - ./mariadb/data:/var/lib/mysql
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: random
      MYSQL_DATABASE: mydb

  exampleweb:
    image: nginx:1.15.8-alpine
    restart: on-failure
    container_name: exampleweb
    volumes:
      - ./web:/code
      - ./nginx/exampleweb.conf:/etc/nginx/conf.d/default.conf
    links:
      - mariadb
      - phpfpm
    ports:
      - "8080:80"